#+TITLE: Emacs support for Python
#+PROPERTY: header-args :tangle ~/.emacs.d/site-lisp/emacs-python.el

* Python

Turn on *linum-mode* when editing Python files.

#+BEGIN_SRC emacs-lisp
(add-hook 'python-mode-hook 'linum-mode)
(add-hook 'python-mode-hook 'sf/whitespace)
#+END_SRC

* Virtual Environments

When working on Python code, you should strongly consider using [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][virtual
environments]] to isolate dependencies.  This allows you a clean way to
specify which version of python and associated modules your project
depends on.

* Anaconda

[[https://github.com/proofit404/anaconda-mode][Anaconda]] is a code navigation, documentation lookup, and completion mode
for [[https://www.python.org/][python]].

#+BEGIN_SRC emacs-lisp
  (use-package anaconda-mode
    :ensure t
    :init
    (add-hook 'python-mode-hook 'anaconda-mode)
    (add-hook 'python-mode-hook 'anaconda-eldoc-mode)
    :config
    (setq anaconda-mode-installation-directory (concat user-emacs-directory "user/anaconda-mode"))
    )
#+END_SRC

Useful commands in =anaconda-mode=:

| Keybinding | Description                    |
|------------+--------------------------------|
| C-M-i      | anaconda-mode-complete         |
| M-.        | anaconda-mode-find-definitions |
| M-,        | anaconda-mode-find-assignments |
| M-r        | anaconda-mode-find-references  |
| M-*        | anaconda-mode-go-back          |
| M-?        | anaconda-mode-show-doc         |

To get better completion, use [[https://company-mode.github.io/][company-mode]] and [[https://github.com/proofit404/company-anaconda][company-anaconda]].

* Module boilerplate

Finally, offer module for use.

#+BEGIN_SRC emacs-lisp
(provide 'emacs-python)
#+END_SRC

* License

This document is licensed under the GNU Free Documentation License
version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

#+BEGIN_SRC 
Copyright (C) 2017 Stephen Fromm

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code in this document is free software: you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

This code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
#+END_SRC
