#+TITLE: README
#+AUTHOR: Stephen Fromm

* Forge

This is my forge for getting stuff done.  It is based in [[https://www.gnu.org/software/emacs/][Emacs]].  This is how I manage [[https://notmuchmail.org/][mail]], software
development, journaling, project tracking, and more.

At one time, this configuration was based on the ideas of [[http://orgmode.org/worg/org-contrib/babel/intro.html#literate-programming][literate programming]].  While I have moved
away from that for managing my Emacs configuration, I think there are a lot of positive elements to
it that I still use in other projects.  As part of this rewrite, I opted to move away from this
approach to managing /emacs.d/.

This environment is managed by the included Makefile.  It only has two targets:  Install Emacs and
update the installed packages.

** Installation

First things first.  Clone the git repository:

#+BEGIN_EXAMPLE
$ git clone https://github.com/sfromm/dot-emacs.d ~/.emacs.d
#+END_EXAMPLE

If you do not already have Emacs installed, you can use the =make install= target.  On MacOSX, this
will use [[https://brew.sh/][Homebrew]] to install Emacs.

On the first time you run /emacs-forge/, it will go through and install several packages.  This may
take awhile, so please be patient.  You can also run the target =make bootstrap= command to install
the main packages needed by /emacs-forge/.

** Updates

You can keep up to date by using the =make update= target.  This will do a few things:

- Do a =git pull= to pull in the latest changes to /emacs-forge/.
- Run the function =forge/update-packages= to update the installed Emacs packages.


** Configuration

There are a couple directories you use to store any personal or site-specific configuration for
/emacs-forge/:

- *~/.emacs.d/preload* (=forge-preload-dir)  Files to preload before loading forge modules.
- *~/.emacs.d/site* (=forge-site-dir=)
- *~/.emacs.d/user*  (=forge-personal-dir=)
