#+TITLE: Core Emacs Setup
#+PROPERTY: header-args :tangle ~/.emacs.d/site-lisp/setup-core.el

* Helper functions
#+BEGIN_SRC emacs-lisp
  (defun sf/system-type-is-darwin ()
    "Return true if system is Darwin/MacOS"
    (string-equal system-type "darwin")
    )

  (defun sf/system-type-is-windows ()
    "Return true if system is Windows"
    (string-equal system-type "windows-nt")
    )

  (defun sf/system-type-is-linux ()
    "Return true if system is GNU/Linux"
    (string-equal system-type "gnu/linux")
    )
#+END_SRC

* Platform issues

** MacOS

The default PATH on MacOS needs some help, particularly if you use
[[https://brew.sh/][Homebrew]].

#+BEGIN_SRC emacs-lisp
  (when (sf/system-type-is-darwin)
    (setenv "PATH" (concat "/usr/local/bin:" (getenv "PATH")))
    )
#+END_SRC

* Postamble

Finally, offer module for use.

#+BEGIN_SRC emacs-lisp
(provide 'setup-core)
#+END_SRC

* License

This document is licensed under the GNU Free Documentation License
version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

#+BEGIN_QUOTE
Copyright (C) 2017 Stephen Fromm

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code in this document is free software: you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

This code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
#+END_QUOTE
