#+TITLE: Emacs support for Python
#+PROPERTY: header-args :tangle ~/.emacs.d/site-lisp/setup-python.el

* Python

Turn on *linum-mode* when editing Python files.

#+BEGIN_SRC emacs-lisp
  (use-package python
    :interpreter ("python" . python-mode)
    :config
    (setq python-indent-offset 4)
    (add-hook 'python-mode-hook 'linum-mode)
    (add-hook 'python-mode-hook 'sf/whitespace))
#+END_SRC

* Virtual Environments

When working on Python code, you should strongly consider using [[http://docs.python-guide.org/en/latest/dev/virtualenvs/][virtual
environments]] to isolate dependencies.  This allows you a clean way to
specify which version of python and associated modules your project
depends on.

* Elpy

[[https://elpy.readthedocs.io/en/latest/index.html][Elpy]] is an Emacs Python Development Environment.  It aims to provide an
easy to install, fully featured environment for Python development.

The author recommends to add the following package archive to get the
latest version.  MELPA seems current enough.

#+BEGIN_SRC emacs-lisp :tangle no
(add-to-list 'package-archives
             '("elpy" . "http://jorgenschaefer.github.io/packages/"))
#+END_SRC

Once installed, go ahead and configure it.

#+BEGIN_SRC emacs-lisp
  (use-package elpy
    :commands elpy-enable
    :config
    (electric-indent-local-mode -1))
#+END_SRC

Useful commands in =elpy-mode=:

| Keybinding | Description                       |
|------------+-----------------------------------|
| C-c C-f    | Find Python file                  |
| C-c C-s    | Search for Python symbol          |
| C-c C-z    | Switch to Python shell            |
| C-c C-c    | Send region to Python interpreter |

* Jedi

For auto-completion, there is [[https://github.com/tkf/emacs-jedi][Jedi]].  

#+BEGIN_SRC emacs-lisp
  (use-package jedi
    :init
    (add-to-list 'company-backends 'company-jedi)
    :config
    (use-package company-jedi
      :init
      (add-hook 'python-mode-hook (lambda () (add-to-list 'company-backends 'company-jedi)))
      (setq company-jedi-python-bin "python")))
#+END_SRC

* Module boilerplate

Finally, offer module for use.

#+BEGIN_SRC emacs-lisp
(provide 'setup-python)
#+END_SRC

* License

This document is licensed under the GNU Free Documentation License
version 1.3 or later (http://www.gnu.org/copyleft/fdl.html).

#+BEGIN_SRC 
Copyright (C) 2017 Stephen Fromm

Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3
or any later version published by the Free Software Foundation;
with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.

Code in this document is free software: you can redistribute it
and/or modify it under the terms of the GNU General Public
License as published by the Free Software Foundation, either
version 3 of the License, or (at your option) any later version.

This code is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
#+END_SRC
